name: CI

on: [pull_request, push]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Cache Cargo artifacts
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-${{ github.job }}-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run clippy lints
        run: cargo clippy --locked --workspace --all-targets --all-features -- --deny warnings

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Cache Cargo artifacts
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-${{ github.job }}-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo +nightly fmt --all -- --check

  doc:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Cache Cargo artifacts
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
            cargo-${{ runner.os }}-${{ github.job }}-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Check documentation
        run: cargo doc --locked --workspace --all-features --document-private-items --no-deps
        env:
          RUSTDOCFLAGS: -D warnings

  # test:
  #   name: Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v7
  #       with:
  #         persist-credentials: false
  #
  #     - name: Cache Cargo artifacts
  #       uses: actions/cache@v6
  #       with:
  #         path: |
  #           ~/.cargo/bin/
  #           ~/.cargo/registry/index/
  #           ~/.cargo/registry/cache/
  #           ~/.cargo/git/db/
  #           target/
  #         key: cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-${{ hashFiles('**/Cargo.lock') }}
  #         restore-keys: |
  #           cargo-${{ runner.os }}-${{ github.job }}-${{ github.ref_name }}-
  #           cargo-${{ runner.os }}-${{ github.job }}-
  #
  #     - name: Install Rust toolchain
  #       uses: dtolnay/rust-toolchain@stable
  #
  #     - name: Run tests
  #       run: |
  #         cargo test --locked --workspace --all-features --all-targets
  #         # Workaround for https://github.com/rust-lang/cargo/issues/6669
  #         cargo test --locked --workspace --all-features --doc
